#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : singledispatch
Version  : 3.6.1
Release  : 38
URL      : https://files.pythonhosted.org/packages/57/f7/4e2c333915f0ea1a4e16ed50d9a420b453c4096d8b3c9b6e721211b5b47d/singledispatch-3.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/57/f7/4e2c333915f0ea1a4e16ed50d9a420b453c4096d8b3c9b6e721211b5b47d/singledispatch-3.6.1.tar.gz
Summary  : Backport functools.singledispatch from Python 3.4 to Python 2.6-3.3.
Group    : Development/Tools
License  : MIT
Requires: singledispatch-license = %{version}-%{release}
Requires: singledispatch-python = %{version}-%{release}
Requires: singledispatch-python3 = %{version}-%{release}
Requires: ordereddict
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : ordereddict
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/singledispatch.svg
:target: `PyPI link`_

%package license
Summary: license components for the singledispatch package.
Group: Default

%description license
license components for the singledispatch package.


%package python
Summary: python components for the singledispatch package.
Group: Default
Requires: singledispatch-python3 = %{version}-%{release}

%description python
python components for the singledispatch package.


%package python3
Summary: python3 components for the singledispatch package.
Group: Default
Requires: python3-core
Provides: pypi(singledispatch)
Requires: pypi(six)

%description python3
python3 components for the singledispatch package.


%prep
%setup -q -n singledispatch-3.6.1
cd %{_builddir}/singledispatch-3.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614361719
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/singledispatch
cp %{_builddir}/singledispatch-3.6.1/LICENSE %{buildroot}/usr/share/package-licenses/singledispatch/8e6689d37f82d5617b7f7f7232c94024d41066d1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/singledispatch/8e6689d37f82d5617b7f7f7232c94024d41066d1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
